# -*- coding: utf-8 -*-
"""fibonacci or unique num counter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eayAzoxOoWucd7b7Lz3TkWLyyKCYrKb
"""

import sys #just in case :D
import re

def temizler(input_variable):
  #Necessary imports : import re, import sys
  #This function gets the input, lowercases it, splits the words and ignore everything but A-Za-z0-9ğüşıçöa
  #to use this function properly you must call it with one object like: input_pre_processor('deneme') or input_pre_processor(list_a)
  #to add more operations to this function you can try like above pro1 = [sub1.function(operation) for sub1 in pro1]
  input_variable = str(input_variable)
  pro1 = [sub1 for sub1 in input_variable.split(' ')]
  pro1 = [sub1.lower() for sub1 in input_variable.split(' ')] #lowercases the input
  pro1 = [re.sub('[^A-Za-z0-9ğüşıçöiİŞ]+', ' ',sub1) for sub1 in pro1] #uses regex and removes nothing bu given parameters
  pro1 = [sub1.strip(' ') for sub1 in pro1] # makes words and sentences seperated from each other
  
  print(pro1)
  return pro1

def num_counter(x):
  word_list = [] #we create an empty list for all inputs 
  number_of_inputs = x #get the number of inputs to iterate over while loop
  error_count = 0  #if there happens to be an error more than five times counter initiates 
  i = 0 # starting number of input loop
  while i < x: # loop will create desired number of words or word groups will be implemented.
    input_parameter = str(input('Lütfen kelime olarak giriş yapınız:'))  #numbers can also be defined as words that's why it is taken as str but it can be changed up on request
    try:
      for q in range(len(temizler(input_parameter))):
        word_list.append(temizler(input_parameter)[q])
      i+=1
    except:
      print('Girilen parametre uygun değildir. Lütfen kelime ya da kelime grupları girişi yapınız')
      error_count += 1
      if error_count > 5:
        print('5 defa yanlış giriş yaptınız program durdurulacaktır!')
        break
      else:
        continue
      
  word_freq = []
  for w in word_list:
    word_freq.append(word_list.count(w))
  word_dict = dict(zip(word_list, word_freq)) 
  for key,value in word_dict.items():
    if value == 1:
         print(key)

def fibonacci(number):
  n = number
  if n ==0 or n==1:
    return n
  return fibonacci(n-1)+fibonacci(n-2)

print('Merhabalar. Hoş Geldiniz.')
print('Çalıştırdığınız bu uygulama 2 ayrı fonksyonda çalışmaktadır.')
print('1.Fonksyonda, size girdiğiniz sayıya karşılık geren fibonacci sayısı gösterilmektedir.')
print('2.Fonksyonda ise öncelikle kaç adet kelime gireceğiniz sorulmakta, \ndaha sonra girdiğiniz kelimelerden eşsiz olanlar gösterilmektedir.')
print('Lütfen 1. Fonksyon için 1 e, 2. Fonksyon için ise 2ye basınız')
print('Program kullanıldıktan sonra kapanacaktır. Tekrar kullanmak \niçin programı tekrar çalıştırmanız gerekmektedir.')

error_count = 0
while True:
  loadx = input('Lütfen hangi fonksyonu çalıştırmak istediğinizi seçiniz\n1 - Fibonacci\n2 - Eşsiz Kelime Bulucu\n')
  try:
    sayisal = int(loadx)
    
    if sayisal == 1 :
      number = input('Lütfen kaçıncı fibonacci sayısını istediğinizi tamsayı, rakam olarak giriniz:\nörnek: 1 için 1, 7 için 7 yazıp enter a basınız')
      try:
        number = int(number)
        result = (fibonacci((number)))
        print(str(number)+'th fibonacci is:')
        print(result)
        break
      except:
        print('Lütfen bir sayı giriniz.\nprogram baştan başlayacaktır.')
        error_count +=1
        if error_count > 5:
          print('5 defa yanlış giriş yaptınız program durdurulacaktır!')
          break
    elif sayisal == 2:
      num_of_words = input('Lütfen kaç adet giriş yapacağınızı rakam olarak giriniz:\nörnek: 1 için 1, 7 için 7 yazıp enter a basınız')
      try:
        num_of_words = int(num_of_words)
        num_counter(num_of_words)
        break
      except ValueError:
        print('Yapmış olduğunuz giriş 1 ya da 2 rakamı dışında olduğu için işleminize devam edemiyorum\nLütfen tekrar deneyiniz...')
        error_count +=1
        if error_count > 5:
          print('5 defa yanlış giriş yaptınız program durdurulacaktır!')
          break
        continue
    else:
      print('Yapmış olduğunuz giriş rakam olmadığı için işleminize devam edemiyorum\nLütfen tekrar deneyiniz...')
      error_count +=1
      if error_count > 5:
        print('5 defa yanlış giriş yaptınız program durdurulacaktır!')
        break
  except ValueError:
    print('Yapmış olduğunuz giriş 1 ya da 2 rakamı dışında olduğu için işleminize devam edemiyorum\nLütfen tekrar deneyiniz...')
    error_count +=1
    if error_count > 5:
      print('5 defa yanlış giriş yaptınız program durdurulacaktır!')
      break
    continue